version: "3.9"
services:
  node-red:
    image: nodered/node-red:1.2.6
    restart: always
    environment:
      - TZ=Asia/Jerusalem
    ports:
      - "1880:1880"
    volumes:
      - ./node-red/data:/data